import pytest
from unittest.mock import AsyncMock, MagicMock
from httpx import AsyncClient, ASGITransport


def _make_mocks():
    """Create standard mock vault and router for use in tests."""
    from app.engine.router import HybridRouter
    from app.engine.vault import Vault

    mock_router = AsyncMock(spec=HybridRouter)
    mock_router.complete = AsyncMock(return_value="Regulation X requires compliance.")

    mock_vault = MagicMock(spec=Vault)
    mock_vault.seal_and_schedule.return_value = "test-session-id"
    mock_vault.open.return_value = {"PERSON_001": "Max Mustermann"}
    mock_vault.purge.return_value = None

    return mock_router, mock_vault


@pytest.mark.asyncio
async def test_chat_endpoint_returns_200():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine, ComplianceResult
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog

    mock_router, mock_vault = _make_mocks()

    mock_shield = MagicMock(spec=ShieldEngine)
    mock_shield.mask.return_value = MaskResult(
        masked_text="PERSON_001 wants to know about regulations.",
        mapping={"PERSON_001": "Max Mustermann"},
        pii_stats={"PERSON": 1},
    )
    mock_shield.deanonymize.return_value = "Max Mustermann wants to know about regulations."
    mock_shield.watermark.return_value = "Max Mustermann wants to know about regulations. Note: this response was generated by an AI system."

    mock_guardian = AsyncMock(spec=GuardianEngine)
    mock_guardian.check.return_value = ComplianceResult(compliant=True)

    mock_cache = MagicMock(spec=VectorCache)
    mock_cache.get.return_value = None

    mock_audit = AsyncMock(spec=AuditLog)

    app = create_app(
        shield=mock_shield,
        guardian=mock_guardian,
        cache=mock_cache,
        audit=mock_audit,
        router=mock_router,
        vault=mock_vault,
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post("/v1/chat", json={
            "messages": [{"role": "user", "content": "Max Mustermann wants to know about regulations."}]
        }, headers={"X-Org-ID": "test-org", "X-User-Role": "analyst"})

    assert resp.status_code == 200
    data = resp.json()
    assert "Max Mustermann" in data["content"]
    mock_shield.mask.assert_called_once()
    mock_audit.write.assert_called_once()


@pytest.mark.asyncio
async def test_compliance_failure_returns_451():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine, ComplianceError
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog

    mock_router, mock_vault = _make_mocks()
    mock_router.complete = AsyncMock(return_value="illegal content")
    mock_vault.open.return_value = {}

    mock_shield = MagicMock(spec=ShieldEngine)
    mock_shield.mask.return_value = MaskResult(masked_text="bad prompt", mapping={}, pii_stats={})
    mock_shield.deanonymize.return_value = "bad response"
    mock_shield.watermark.return_value = "bad response"

    mock_guardian = AsyncMock(spec=GuardianEngine)
    mock_guardian.check.side_effect = ComplianceError("illegal content", "Art. 5(1)(a)")

    mock_cache = MagicMock(spec=VectorCache)
    mock_cache.get.return_value = None

    mock_audit = AsyncMock(spec=AuditLog)

    app = create_app(
        shield=mock_shield,
        guardian=mock_guardian,
        cache=mock_cache,
        audit=mock_audit,
        router=mock_router,
        vault=mock_vault,
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post("/v1/chat", json={"messages": [{"role": "user", "content": "bad"}]},
                                 headers={"X-Org-ID": "test-org", "X-User-Role": "analyst"})
    assert resp.status_code == 451


@pytest.mark.asyncio
async def test_audit_failure_returns_500():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine, ComplianceResult
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog

    mock_router, mock_vault = _make_mocks()
    mock_router.complete = AsyncMock(return_value="response")
    mock_vault.open.return_value = {}

    mock_shield = MagicMock(spec=ShieldEngine)
    mock_shield.mask.return_value = MaskResult(masked_text="prompt", mapping={}, pii_stats={})
    mock_shield.deanonymize.return_value = "response"
    mock_shield.watermark.return_value = "response"

    mock_guardian = AsyncMock(spec=GuardianEngine)
    mock_guardian.check.return_value = ComplianceResult(compliant=True)

    mock_cache = MagicMock(spec=VectorCache)
    mock_cache.get.return_value = None

    mock_audit = AsyncMock(spec=AuditLog)
    mock_audit.write.side_effect = Exception("DB connection lost")

    app = create_app(
        shield=mock_shield,
        guardian=mock_guardian,
        cache=mock_cache,
        audit=mock_audit,
        router=mock_router,
        vault=mock_vault,
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post("/v1/chat", json={"messages": [{"role": "user", "content": "test"}]},
                                 headers={"X-Org-ID": "test-org", "X-User-Role": "analyst"})
    assert resp.status_code == 500


@pytest.mark.asyncio
async def test_audit_export_requires_auth():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog
    import os
    os.environ["AUDIT_TOKEN"] = "test-token"

    mock_router, mock_vault = _make_mocks()

    mock_audit = AsyncMock(spec=AuditLog)
    mock_audit.fetch_range.return_value = [
        {"request_id": "req-1", "ts": "2026-01-01T00:00:00+00:00", "compliant": True,
         "article_ref": None, "watermark_seed": "abc", "duration_ms": 100}
    ]
    app = create_app(
        shield=MagicMock(spec=ShieldEngine),
        guardian=AsyncMock(spec=GuardianEngine),
        cache=MagicMock(spec=VectorCache),
        audit=mock_audit,
        router=mock_router,
        vault=mock_vault,
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.get("/audit/export")
        assert resp.status_code == 403 or resp.status_code == 401
        resp = await client.get("/audit/export", headers={"Authorization": "Bearer test-token"})
        assert resp.status_code == 200
        assert resp.headers["content-type"] == "application/pdf"


@pytest.mark.asyncio
async def test_health_endpoint():
    from app.main import create_app
    from app.engine.shield import ShieldEngine
    from app.engine.guardian import GuardianEngine
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog

    mock_router, mock_vault = _make_mocks()

    app = create_app(
        shield=MagicMock(spec=ShieldEngine),
        guardian=AsyncMock(spec=GuardianEngine),
        cache=MagicMock(spec=VectorCache),
        audit=AsyncMock(spec=AuditLog),
        router=mock_router,
        vault=mock_vault,
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.get("/health")
    assert resp.status_code == 200
    assert resp.json() == {"status": "ok"}


# --- RBAC / identity header tests ---
from app.middleware.auth import RequestIdentity
from app.engine.router import HybridRouter


@pytest.mark.asyncio
async def test_chat_uses_route_for_identity():
    """routes.py must call state.router.route_for(identity) not state.router directly."""
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine, ComplianceResult
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog
    from app.engine.vault import Vault

    mock_shield = MagicMock(spec=ShieldEngine)
    mock_shield.mask.return_value = MaskResult(
        masked_text="PERSON_001 asks about regulations.",
        mapping={"PERSON_001": "Alice"},
        pii_stats={"PERSON": 1},
    )
    mock_shield.deanonymize.return_value = "Alice asks about regulations."
    mock_shield.watermark.return_value = "Alice asks about regulations."

    mock_guardian = AsyncMock(spec=GuardianEngine)
    mock_guardian.check.return_value = ComplianceResult(compliant=True)
    mock_cache = MagicMock(spec=VectorCache)
    mock_cache.get.return_value = None
    mock_audit = AsyncMock(spec=AuditLog)
    mock_vault = MagicMock(spec=Vault)
    mock_vault.seal_and_schedule.return_value = "sid-001"
    mock_vault.open.return_value = {"PERSON_001": "Alice"}

    mock_sub_router = AsyncMock()
    mock_sub_router.complete = AsyncMock(return_value="Regulation response.")
    mock_router = MagicMock(spec=HybridRouter)
    mock_router.route_for.return_value = mock_sub_router

    app = create_app(
        shield=mock_shield, guardian=mock_guardian, cache=mock_cache,
        audit=mock_audit, router=mock_router, vault=mock_vault,
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post(
            "/v1/chat",
            json={"messages": [{"role": "user", "content": "Alice asks about regulations."}]},
            headers={"X-Org-ID": "rd", "X-User-Role": "analyst"},
        )
    assert resp.status_code == 200
    mock_router.route_for.assert_called_once()


@pytest.mark.asyncio
async def test_chat_without_identity_headers_returns_403():
    """Missing identity headers → 403 (middleware rejects before handler runs)."""
    from app.main import create_app
    from app.engine.shield import ShieldEngine
    from app.engine.guardian import GuardianEngine
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog
    from app.engine.vault import Vault

    app = create_app(
        shield=MagicMock(spec=ShieldEngine),
        guardian=AsyncMock(spec=GuardianEngine),
        cache=MagicMock(spec=VectorCache),
        audit=AsyncMock(spec=AuditLog),
        router=MagicMock(spec=HybridRouter),
        vault=MagicMock(spec=Vault),
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post("/v1/chat", json={"messages": [{"role": "user", "content": "hi"}]})
    assert resp.status_code == 403


@pytest.mark.asyncio
async def test_streaming_response():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine, ComplianceResult
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog
    from app.engine.router import HybridRouter
    from app.engine.vault import Vault
    from unittest.mock import AsyncMock, MagicMock

    mock_router = MagicMock(spec=HybridRouter)
    mock_router.complete = AsyncMock(return_value="Hello world")

    async def fake_stream(prompt):
        for word in ["Hello", " world"]:
            yield word

    mock_router.stream = fake_stream

    mock_vault = MagicMock(spec=Vault)
    mock_vault.seal_and_schedule.return_value = "stream-session-id"
    mock_vault.open.return_value = {"PERSON_001": "Max Mustermann"}
    mock_vault.purge.return_value = None

    mock_shield = MagicMock(spec=ShieldEngine)
    mock_shield.mask.return_value = MaskResult(
        masked_text="PERSON_001 asks something.",
        mapping={"PERSON_001": "Max Mustermann"},
        pii_stats={"PERSON": 1},
    )
    mock_shield.deanonymize.return_value = "Max Mustermann asks something."
    mock_shield.watermark.return_value = "Max Mustermann asks something. [AI]"

    mock_guardian = AsyncMock(spec=GuardianEngine)
    mock_guardian.check.return_value = ComplianceResult(compliant=True)

    mock_cache = MagicMock(spec=VectorCache)
    mock_cache.get.return_value = None

    mock_audit = AsyncMock(spec=AuditLog)

    app = create_app(
        shield=mock_shield,
        guardian=mock_guardian,
        cache=mock_cache,
        audit=mock_audit,
        router=mock_router,
        vault=mock_vault,
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post("/v1/chat", json={
            "messages": [{"role": "user", "content": "Max Mustermann asks something."}],
            "stream": True,
        }, headers={"X-Org-ID": "test-org", "X-User-Role": "analyst"})

    assert resp.status_code == 200
    assert "text/event-stream" in resp.headers["content-type"]
