import pytest
from unittest.mock import AsyncMock, MagicMock
from httpx import AsyncClient, ASGITransport


@pytest.mark.asyncio
async def test_chat_endpoint_returns_200():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine, ComplianceResult
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog

    mock_shield = MagicMock(spec=ShieldEngine)
    mock_shield.mask.return_value = MaskResult(
        masked_text="PERSON_001 wants to know about regulations.",
        mapping={"PERSON_001": "Max Mustermann"}
    )
    mock_shield.deanonymize.return_value = "Max Mustermann wants to know about regulations."
    mock_shield.watermark.return_value = "Max Mustermann wants to know about regulations. Note: this response was generated by an AI system."

    mock_guardian = AsyncMock(spec=GuardianEngine)
    mock_guardian.check.return_value = ComplianceResult(compliant=True)

    mock_cache = MagicMock(spec=VectorCache)
    mock_cache.get.return_value = None

    mock_audit = AsyncMock(spec=AuditLog)

    app = create_app(
        shield=mock_shield,
        guardian=mock_guardian,
        cache=mock_cache,
        audit=mock_audit,
        vllm_call=AsyncMock(return_value="Regulation X requires compliance."),
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post("/v1/chat", json={
            "messages": [{"role": "user", "content": "Max Mustermann wants to know about regulations."}]
        })

    assert resp.status_code == 200
    data = resp.json()
    assert "Max Mustermann" in data["content"]
    mock_shield.mask.assert_called_once()
    mock_audit.write.assert_called_once()


@pytest.mark.asyncio
async def test_compliance_failure_returns_451():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine, ComplianceError
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog

    mock_shield = MagicMock(spec=ShieldEngine)
    mock_shield.mask.return_value = MaskResult(masked_text="bad prompt", mapping={})
    mock_shield.deanonymize.return_value = "bad response"
    mock_shield.watermark.return_value = "bad response"

    mock_guardian = AsyncMock(spec=GuardianEngine)
    mock_guardian.check.side_effect = ComplianceError("illegal content", "Art. 5(1)(a)")

    mock_cache = MagicMock(spec=VectorCache)
    mock_cache.get.return_value = None

    mock_audit = AsyncMock(spec=AuditLog)

    app = create_app(
        shield=mock_shield,
        guardian=mock_guardian,
        cache=mock_cache,
        audit=mock_audit,
        vllm_call=AsyncMock(return_value="illegal content"),
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post("/v1/chat", json={"messages": [{"role": "user", "content": "bad"}]})
    assert resp.status_code == 451


@pytest.mark.asyncio
async def test_audit_failure_returns_500():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine, ComplianceResult
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog

    mock_shield = MagicMock(spec=ShieldEngine)
    mock_shield.mask.return_value = MaskResult(masked_text="prompt", mapping={})
    mock_shield.deanonymize.return_value = "response"
    mock_shield.watermark.return_value = "response"

    mock_guardian = AsyncMock(spec=GuardianEngine)
    mock_guardian.check.return_value = ComplianceResult(compliant=True)

    mock_cache = MagicMock(spec=VectorCache)
    mock_cache.get.return_value = None

    mock_audit = AsyncMock(spec=AuditLog)
    mock_audit.write.side_effect = Exception("DB connection lost")

    app = create_app(
        shield=mock_shield,
        guardian=mock_guardian,
        cache=mock_cache,
        audit=mock_audit,
        vllm_call=AsyncMock(return_value="response"),
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.post("/v1/chat", json={"messages": [{"role": "user", "content": "test"}]})
    assert resp.status_code == 500


@pytest.mark.asyncio
async def test_audit_export_requires_auth():
    from app.main import create_app
    from app.engine.shield import ShieldEngine, MaskResult
    from app.engine.guardian import GuardianEngine
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog
    import os
    os.environ["AUDIT_TOKEN"] = "test-token"

    mock_audit = AsyncMock(spec=AuditLog)
    mock_audit.fetch_range.return_value = [
        {"request_id": "req-1", "ts": "2026-01-01T00:00:00+00:00", "compliant": True,
         "article_ref": None, "watermark_seed": "abc", "duration_ms": 100}
    ]
    app = create_app(
        shield=MagicMock(spec=ShieldEngine),
        guardian=AsyncMock(spec=GuardianEngine),
        cache=MagicMock(spec=VectorCache),
        audit=mock_audit,
        vllm_call=AsyncMock(return_value="test"),
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.get("/audit/export")
        assert resp.status_code == 403 or resp.status_code == 401
        resp = await client.get("/audit/export", headers={"Authorization": "Bearer test-token"})
        assert resp.status_code == 200
        assert resp.headers["content-type"] == "application/pdf"


@pytest.mark.asyncio
async def test_health_endpoint():
    from app.main import create_app
    from app.engine.shield import ShieldEngine
    from app.engine.guardian import GuardianEngine
    from app.database.vector_cache import VectorCache
    from app.database.audit_log import AuditLog

    app = create_app(
        shield=MagicMock(spec=ShieldEngine),
        guardian=AsyncMock(spec=GuardianEngine),
        cache=MagicMock(spec=VectorCache),
        audit=AsyncMock(spec=AuditLog),
        vllm_call=AsyncMock(return_value=""),
    )
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.get("/health")
    assert resp.status_code == 200
    assert resp.json() == {"status": "ok"}
