# gateway/compliance/judge.py
from dataclasses import dataclass, field

from .rules import RULES


@dataclass
class ComplianceResult:
    compliant: bool
    violations: list[str] = field(default_factory=list)


class GuardianJudge:
    def __init__(self, max_rewrites: int = 3) -> None:
        self.max_rewrites = max_rewrites

    def check(self, text: str) -> ComplianceResult:
        violations: list[str] = []
        for rule in RULES:
            if rule.pattern.search(text):
                violations.append(f"[{rule.article}] {rule.description}")
        return ComplianceResult(compliant=len(violations) == 0, violations=violations)

    async def _rewrite(self, text: str, violations: list[str]) -> str:
        """
        Default rewrite: redact matched phrases and append transparency notice.
        In production, replace this body with a secondary LLM call.
        """
        result = text
        for rule in RULES:
            result = rule.pattern.sub("[REDACTED]", result)
        if any("Art.12" in v for v in violations):
            result += " [Note: This response was generated by an AI system.]"
        return result

    async def enforce(self, text: str) -> tuple[str, int]:
        """Rewrite until compliant or max_rewrites reached. Returns (text, rewrite_count)."""
        current = text
        rewrites = 0
        for _ in range(self.max_rewrites):
            result = self.check(current)
            if result.compliant:
                return current, rewrites
            current = await self._rewrite(current, result.violations)
            rewrites += 1
        return current, rewrites
