import hashlib
import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine
from presidio_anonymizer.entities import OperatorConfig

from app.config import get_settings


@dataclass
class MaskResult:
    masked_text: str
    mapping: dict  # pseudonym → original (reverse map for de-anonymization)



# Entity types that are NOT personally identifiable under GDPR / EU AI Act.
# DATE_TIME, NRP (nationalities/religions/political groups used as generic labels),
# and LOCATION (city/country names without linkage) are excluded from masking.
_NON_PII_ENTITY_TYPES: frozenset[str] = frozenset({
    "DATE_TIME",
    "NRP",
    "LOCATION",
})


class ShieldEngine:
    def __init__(self, synonym_pairs_path: Optional[str] = None):
        self._analyzer = AnalyzerEngine()
        self._anonymizer = AnonymizerEngine()
        # No shared mutable state per request — each mask() call returns a new
        # MaskResult with its own mapping dict, so no lock is needed.
        pairs_path = synonym_pairs_path or get_settings().shield_synonym_pairs_path
        with open(pairs_path) as f:
            self._synonym_pairs: list[list[str]] = json.load(f)["pairs"]

    def mask(self, text: str) -> MaskResult:
        """Detect PII, replace with pseudonyms, return reverse mapping for de-anonymization."""
        raw_results = self._analyzer.analyze(text=text, language="en")
        # Filter out entity types that are not personally identifiable data
        results = [r for r in raw_results if r.entity_type not in _NON_PII_ENTITY_TYPES]
        if not results:
            return MaskResult(masked_text=text, mapping={})

        # Build entity-type counters for sequential pseudonym names
        counters: dict[str, int] = {}
        forward: dict[str, str] = {}  # original → pseudonym
        operators: dict[str, OperatorConfig] = {}

        for r in sorted(results, key=lambda x: x.start):
            original = text[r.start:r.end]
            entity_type = r.entity_type
            counters[entity_type] = counters.get(entity_type, 0) + 1
            pseudonym = f"{entity_type}_{counters[entity_type]:03d}"
            if original not in forward:
                forward[original] = pseudonym
            operators[entity_type] = OperatorConfig(
                "replace", {"new_value": forward[original]}
            )

        anonymized = self._anonymizer.anonymize(
            text=text, analyzer_results=results, operators=operators
        )
        # Reverse mapping: pseudonym → original (for de-anonymization)
        reverse = {v: k for k, v in forward.items()}
        return MaskResult(masked_text=anonymized.text, mapping=reverse)

    def deanonymize(self, text: str, mapping: dict) -> str:
        """Restore pseudonyms to original values using the request-scoped reverse map."""
        result = text
        for pseudonym, original in mapping.items():
            result = result.replace(pseudonym, original)
        return result

    def watermark(self, text: str, request_id: str) -> str:
        """Inject synonym substitutions seeded by request_id for forensic traceability.

        Max 4 total calls budget: 1 judge call + up to 3 correction calls.
        The seed is logged in audit so leaked text is traceable to its session.
        """
        seed = int(hashlib.sha256(request_id.encode()).hexdigest()[:8], 16)
        rng = random.Random(seed)
        pairs = self._synonym_pairs[:]
        rng.shuffle(pairs)

        result = text
        injections = 0
        for pair in pairs:
            a, b = pair[0], pair[1]
            src, dst = (a, b) if rng.random() > 0.5 else (b, a)
            if (f" {src} " in result
                    or result.lower().startswith(src + " ")
                    or result.lower().endswith(" " + src)):
                result = result.replace(src, dst, 1)
                injections += 1

        # Fallback: if fewer than 3 substitutions, append a semantically neutral tag
        if injections < 3:
            tags = [
                "Note: this response was generated by an AI system.",
                "This content was produced by an automated assistant.",
                "Generated by an AI language model.",
            ]
            result = result.rstrip() + " " + tags[seed % len(tags)]

        return result
